version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        links:
            - db

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        container_name: mysql

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
